title: [JuliaRobotics]
description: >- # this means to ignore newlines until "baseurl:"
  JuliaRobotics is an organization dedicated to building and promoting robotics tools in the Julia programming language.
url: "http://www.juliarobotics.org"

# Build settings
theme: jekyll-theme-cayman

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
